---
- name: Checkout rentbot
  git: repo=git@gitlab.com:zaro/rentbot.git dest=/srv/rentbot accept_hostkey=yes

- name: Install rentbot requirements.txt
  pip: requirements=/srv/rentbot/requirements.txt

# - name: Install packages based on package.json
#   npm:
#     path: /srv/rentbot/web/
- name: Install packages based on package.json
  shell: npm install
  args:
    chdir: /srv/rentbot/web/

- name: Build static files
  command: /srv/rentbot/web/build.sh

- include: deploy_reverse_proxy.yml

- include: install_restart_service.yml name=naematel

- include: install_timer.yml name=rentbot-scraper
