---
- hosts: rentbot-web
  tasks:
    - include: tasks/check_scaleway_ssd.yml

    - name: Install apt-transport-https
      with_items:
        - apt-transport-https
      apt: name={{item}}

    - name: Add python 3.6 PPA
      apt_repository:
        repo: 'ppa:fkrull/deadsnakes'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python 3.6 & other packages
      with_items:
        - git
        - tmux
        - python3.6
        - python3.6-dev
        - build-essential
        - libdb-dev
        - libssl-dev
      apt: name={{item}} allow_unauthenticated=yes

    - name: Download get-pip
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py
        mode: 0755

    - name: Install pip
      command: python3.6 /tmp/get-pip.py

    - include: tasks/deploy_web_app.yml
