---
- hosts: rentbot-web
  vars:
    nginx_users:
      rentbot: knockknockletmeinbot
  tasks:
    - include: tasks/check_scaleway_ssd.yml

    - name: Install apt-transport-https
      with_items:
        - apt-transport-https
      apt: name={{item}}

    - name: Add python 3.6 PPA
      apt_repository:
        repo: 'ppa:fkrull/deadsnakes'

    - name: Download nodejs repository script
      get_url:
        url: https://deb.nodesource.com/setup_8.x
        dest: /tmp/setup_8.x
        mode: 0755

    - name: Add nodejs repository
      command: bash /tmp/setup_8.x

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python 3.6 & other packages
      with_items:
        - git
        - tmux
        - python3.6
        - python3.6-dev
        - build-essential
        - libdb-dev
        - libssl-dev
        - nodejs
        - nginx-extras
        - logrotate
        - apache2-utils
      apt: name={{item}} allow_unauthenticated=yes

    - name: Download get-pip
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py
        mode: 0755

    - name: Install pip
      command: python3.6 /tmp/get-pip.py

    - name: Add nginx /etc/nginx/.htpasswd
      file: path=/etc/nginx/.htpasswd state=touch owner=root group=root mode=0644

    - name: Add nginx http users
      command: htpasswd -b /etc/nginx/.htpasswd {{ item.key }} {{ item.value }}
      with_dict: "{{ nginx_users }}"


    - include: tasks/deploy_web_app.yml
